### ISSUE TITLE
您好，请问什么时候开源？

### ISSUE THREAD

**Issue by ALISURE** [Z-Zheng/PopNet#1]
我们想在我们的工作中引用你们的文章，请问在哪里可以拿到你们的文章？你们的程序什么时候开源？需要等到会议结束之后吗？

**Comment by Z-Zheng** [comment]
Thanks for your attention.
This paper belongs to a tech report for the competition, which has been submitted to IGRASS 2019.
So, it will be published in IEEE GRSS.
And our complete long paper also will be submitted to arxiv.
Welcome to follow.

And our source code will be released during IGARSS 2019.

**Comment by ALISURE** [comment]
Hello, have you submitted your paper to arxiv? I didn't find your paper in the received list of IGARSS.  https://igarss2019.org/Papers/AcceptedPapers.asp. Besides, are you going to open source in the near future? Thank you.
